config/routes.rb
Rails.application.routes.draw do
    require 'sidekiq/web'
    resources :tasks
    resources :lists
    get 'export', to: 'exportable#export'
    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'lists#index'
    mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks
  belongs_to :user

  # Generate a CSV File of All Movie Records
  def self.to_csv(fields = column_names, options={})
    CSV.generate(options) do |csv|
      all.each do |list|
        list.tasks.all.each do |task|
          csv << [list.title ,task.attributes.values_at(*fields)]
        end
      end
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # Avatar uploader
  mount_uploader :avatar, AvatarUploader

  
  validates_integrity_of  :avatar
  validates_processing_of :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :name, :email, :password, :current_password)}
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/exportable_controller.rb
class ExportableController < ApplicationController
    def export
        @lists = current_user.lists
        respond_to do |format|
            format.csv{ send_data @lists.to_csv,
                        filename: "export.csv",
                        type: 'application/csv',    
                        disposition: 'inline'}
            format.pdf do
                pdf = Prawn::Document.new
                #PDF content
                if !(@lists.empty?)
                    @lists.each do |list|
                        pdf.text list.title
                        if !(list.tasks.empty?)
                            data = list.tasks.collect{ |task| [ task.title, task.due_date ] }
                            pdf.table(data, :cell_style => {
                            :position => :center,
                            :width => 200,
                            :borders => [:bottom, :top]
                            })
                        else
                            pdf.text "List without tasks!", :size => 15, :align => :center
                        end
                        pdf.move_down 20
                    end
                    send_data pdf.render,
                    filename: "export.pdf",
                    type: 'application/pdf',
                    disposition: 'inline'
                end
            end
        end
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  # GET /lists
  # GET /lists.json
  def index
    @user   = current_user
    @lists  = current_user.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_path, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.tasks.each{|task| task.destroy}
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :user_id).merge(user_id: current_user.id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  end
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @lists = current_user.lists.all
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @lists = current_user.lists.all
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :priority, :is_done, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def delete_to_with_icon(text, path, classes)
        form_tag path, :method => :delete do
            button_tag(classes) do
            raw text
            end
        end
    end

    def post_to_with_icon(text, path, classes)
        form_tag path, :method => :delete do
            button_tag(classes) do
            raw text
            end
        end
    end

    def get_to_with_icon(text, path, classes)
        form_tag path, :method => :get do
            button_tag(classes) do
            raw text
            end
        end
    end
end

app/helpers/exportable_helper.rb
module ExportableHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title TodoApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.is-mobile
    / START NAV
    %nav.navbar
      .container
        .navbar-brand
          %a.navbar-item.title{:href => "/", :style => "font-size:40px"}
            To-do&nbsp
            %span.fa.fa-gamepad
          %span.navbar-burger.burger{"data-target" => "navbarMenu"}
            %span
            %span
            %span
        #navbarMenu.navbar-menu
          .navbar-end
            .buttons
              - if user_signed_in?
                .navbar-item.has-dropdown.is-hoverable
                  %a.navbar-link
                    = current_user.name
                  .navbar-dropdown
                    %a.navbar-item{:href => "/users/edit"}
                      %i.fa.fa-edit
                      &nbspEdit profile
                    %a.navbar-item{:href => "/export.csv"}
                      %i.fa.fa-file-o  
                      &nbspExport as CSV
                    %a.navbar-item{:href => "/export.pdf"}
                      %i.fa.fa-file-pdf-o  
                      &nbspExport as pdf
                    %a.navbar-item{"data-method" => "delete", :href => "/users/sign_out", :rel => "nofollow"}
                      %i.fa.fa-sign-out
                      &nbspSign out
              - else
                = link_to "Sign up", new_user_registration_path, class: "navbar-item button is-primary" 
                = link_to "Log in", new_user_session_path, class: "navbar-item button is-light"     
    = yield

app/views/lists/_form.html.haml
.container.is-widescreen
  .section
    = form_with(model: list, local: true) do |form|
      = form.hidden_field :user_id , :value => current_user.id
      - if list.errors.any?
        #error_explanation
          %h2
            = pluralize(list.errors.count, "error")
            prohibited this list from being saved:
          %ul
            - list.errors.full_messages.each do |message|
              %li= message
      .field
        = form.label :title, class: "label"
        = form.text_field :title, id: :list_title, class: "input"
      .actions.buttons
        = form.submit class: "button is-link"
        = link_to 'Cancel', lists_path, class: "button is-danger "

app/views/lists/edit.html.erb
<div class="hero">
    <h1 class="title has-text-centered">Editing List</h1>
</div>
<%= render 'form', list: @list %>

app/views/lists/index.html.haml
%div.tabs.is-centered.is-large.is-boxed
  %ul
    %li.is-active
      %a To do
    %li 
      %a Done
    %li 
      %a Uncompleted
.content.is-widescreen.has-text-centered
  .section.hero
    .hero-body
      %h1.title
        When nothing goes right...
      %h2.subtitle
        go left
.content
  %table.table
    - @lists.each do |list|   
      %thead
        %tr
          %th= list.title
          %th 
          %th 
          %th Due date
          %th= link_to '', edit_list_path(list), class: "fa fa-edit button is-primary is-inverted"
          %th= delete_to_with_icon "", list, method: :delete, data: { confirm: "Are you sure?" }, class:  "fa fa-times button is-danger is-inverted"            
        - list.tasks.select{|task| !task.is_done && task.due_date >= DateTime.now.to_date}.each do |task|
          %tbody 
            %tr
              %td
              %td= task.title
              %td= task.description
              %td= task.due_date
              %td
                = link_to '', edit_task_path(task), class: "fa fa-edit button is-primary is-inverted"
              %td= delete_to_with_icon "", task, method: :delete, data: { confirm: "Are you sure?" }, class:  "fa fa-times button is-danger is-inverted"                             
  %br
.section.container.has-text-centered.is-half
  =link_to 'New list...', new_list_path, class:"button is-primary is-outlined is-large" 
%footer.footer
  -if !(@lists.empty?)
    %a.float{:href => "/tasks/new"}
      %span.fa.fa-plus

app/views/lists/new.html.erb
<div class="hero" style="text-align:center">
    <h1 class="title">New List</h1>
</div>
<br/>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>
<p>
  <strong>User:</strong>
  <%= @list.user %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path, class: "button is-primary is-fullwidth" %>

app/views/pages/home.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Hero title
      </h1>
      <h2 class="subtitle">
        Hero subtitle
      </h2>
    </div>
  </div>
</section>

app/views/tasks/_form.html.haml
.container.is-widescreen
  .section
    = form_with(model: task, local: true) do |form|
      - if task.errors.any?
        #error_explanation
          %h2
            = pluralize(task.errors.count, "error")
            prohibited this task from being saved:
          %ul
            - task.errors.full_messages.each do |message|
              %li= message
      .field
        .control
          = form.label :list_id, class: "label "
          .select.is-primary
            = form.collection_select :list_id, @lists.order(:title), :id, :title, :required => true
      .field
        = form.label :title, class: "label"
        = form.text_field :title, id: :task_title, class: "input is-primary"
      .field
        = form.label :description, class: "label"
        = form.text_area :description, id: :task_description, class: "input is-primary"
      .field
        = form.label :due_date, class: "label"
        .datepicker.input-group.date
          = form.date_select :due_date, id: :task_due_date, class: "form-control"
      .field
        = form.label :priority, class: "label"
        = form.text_field :priority, id: :task_priority, class: "input is-primary"
      .field
        = form.label :is_done, class: "label"
        = form.check_box :is_done, id: :task_is_done   
      .actions
        = form.submit class: "button is-link is-fullwidth"
        

app/views/tasks/edit.html.erb
<div class="hero" style="text-align:center">
    <h1 class="title">Editing Task</h1>
</div>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due date</th>
      <th>Priority</th>
      <th>Is done</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.priority %></td>
        <td><%= task.is_done %></td>
        <td><%= task.list %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @task.is_done %>
</p>

<p>
  <strong>List:</strong>
  <%= @task.list %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', root_path %>